// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';

export function CaptureScreenshot():Promise<void>;

export function GenerateSolution():Promise<entity.Solution>;

export function RegisterShortcuts():Promise<void>;

export function Reset():Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;
