// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureScreenshot() {
  return window['go']['app']['App']['CaptureScreenshot']();
}

export function GenerateSolution() {
  return window['go']['app']['App']['GenerateSolution']();
}

export function RegisterShortcuts() {
  return window['go']['app']['App']['RegisterShortcuts']();
}

export function Reset() {
  return window['go']['app']['App']['Reset']();
}

export function SetLanguage(arg1) {
  return window['go']['app']['App']['SetLanguage'](arg1);
}
