// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureScreenshot():Promise<void>;

export function GenerateSolution():Promise<string>;

export function Reset():Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;
